using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class Slave_AI : MonoBehaviour {

    [SerializeField]
    Transform _destination;

    NavMeshAgent _navMeshAgent;

	void Start () {
        _navMeshAgent = this.GetComponent<NavMeshAgent>();

        if (_navMeshAgent == null)
        {
            Debug.LogError("navmesh not connected to " + gameObject.name);
        }
        else {
            SetDestination();
        }
	}

    void Update() {
        SetDestination();
    }

    void OnCollisionEnter(Collision coll)
    {
        if (coll.gameObject.name == "Magic_cube")
        {
            
        }
    }

    void SetDestination(){
        if(_destination != null){
            Vector3 targetVector = _destination.transform.position;
            _navMeshAgent.SetDestination(targetVector);
        }
    }

}
